config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster:
      branch: main
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-buff-akita.sh
        container: qc.acc_muggy-amethyst-foxhound
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-green-toad.sh
        container: qc.doc_nippy-ivory-hippopotamus
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-white-uguisu.sh
        container: qc.doc_goopy-asparagus-harrier
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-chestnut-cat.sh
        container: qc.doc_muggy-amaranth-chimpanzee
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-seashell-burmese.sh
        container: qc.lic_whiny-smalt-antelope
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-teal-oyster.sh
        container: qc.sec_crappy-dandelion-tapir
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-periwinkle-tuatara.sh
        container: qc.sty_crappy-amethyst-duck
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-yellow-bobcat.sh
        container: qc.uni_woolly-emerald-donkey
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ultramarine-snake.sh
        container: qc.ver_hazy-zucchini-bracke
timeout: 5400
