config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster:
      branch: main
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-scarlet-bobcat.sh
        container: qc.acc_boozy-sapphire-insect
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-rose-horse.sh
        container: qc.doc_stinky-black-kudu
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-red-clam.sh
        container: qc.doc_breezy-lavender-rat
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-sepia-uguisu.sh
        container: qc.doc_thirsty-asparagus-coyote
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-violet-audemer.sh
        container: qc.lic_skanky-crimson-macaw
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-green-quetzal.sh
        container: qc.sec_wiggy-corn-hedgehog
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-beige-caracal.sh
        container: qc.sty_gummy-rose-hyena
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster pytest:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-yellow-javanese.sh
        container: qc.uni_squeaky-violet-chinook
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_forecaster get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-buff-fly.sh
        container: qc.ver_leaky-apricot-dachshund
timeout: 5400
